### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by xNinjaRose** [Malgardian/TQCollector#12]
TQCollector doesn't work, i set the proper vault and AE path and now it says TQCollector has stopped working, its buggy, please fix

**Comment by Malgardian** [comment]
Please give me more info than that. Which version of TQ are you running (disc, Steam, gog / AE, Ragnarök, Atlantis)? What's your TQVault version? What are the relevant paths?

**Comment by xNinjaRose** [comment]
im using the Steam version and i set the right paths for the vault(in my doc path) and TQAE exe path and it saved but now it jus keeps stopping working and doesnt do anything

**Comment by Malgardian** [comment]
Can you screenshot the window with the set paths, please? Or at least write them here?

**Comment by xNinjaRose** [comment]
I cant screenshot since it closes right away now but: 
C:\%UserProfile%\Documents\MyGames\Titan Quest\TQVaultData
C:\Program Files\Steam\steamapps\common\Titan Quest Anniversary Edition

**Comment by Malgardian** [comment]
It seems like your Vault path has a few errors if that's exactly how it's listed in the TQCollector. You can temporarily uncheck the "Use Vaults" box to try to see whether that's the reason.

**Comment by xNinjaRose** [comment]
How does it have errors? thats where the TQ Vault puts its data? and i cant uncheck anything, it automatically closes every time i launch TQ Collector

**Comment by Malgardian** [comment]
I meant this: 
![paths](https://user-images.githubusercontent.com/22580045/61595893-06c28e00-abfd-11e9-835a-6111acffdff3.png)

But if you can't reach that window anymore, you can try editing the config.xml file directly to change <UseVaults>true</UseVaults> to false.

**Comment by xNinjaRose** [comment]
No i change it in the config.xml to false where u said and it STILL refuses to open, it closes right away, app is broken

**Comment by Malgardian** [comment]
Only broken for you, however. Try to delete the whole downloaded folder and redownload TQC. Take a screenshot similar to the one above when you get to that window.

**Comment by Malgardian** [comment]
I assume that it works now as you haven't replied
