### ISSUE TITLE
Hrunting (Sword, Epic)

### ISSUE THREAD

**Issue by Sir-Mac** [Malgardian/TQCollector#14]
Hi, Malgardian,

thank you for the TQ Collector, it is very useful database.

But somehow, the epic sword called "Hrunting" is missing in your database. Could you, please, add the item into the proper TAB and section of the application?

Thanks,
Sir-Mac

**Comment by Malgardian** [comment]
Sorry for the late reply. Github broke my email notifications it seems.

Are you running the latest version? Because on my end it appears just fine in the list?

**Comment by Sir-Mac** [comment]
@Malgardian You are right, in the very last version, the sword "Hrunting" is present and properly calculated within my vault.
