### ISSUE TITLE
"Suit of the Bandit King" set in wrong category

### ISSUE THREAD

**Issue by DarthSomebody** [Malgardian/TQCollector#15]
It's a legendary set, but listed under epic.

![image](https://user-images.githubusercontent.com/10331302/76153702-d833ed80-60cf-11ea-8ac3-4380200637e8.png)

**Comment by Malgardian** [comment]
Sorry for the late reply. Github broke my email notifications.

No, it's an epic set by both the file names (u_**e**_set03.dbr) and its drop location (exclusively epic difficulty).

**Comment by DarthSomebody** [comment]
But it's purple. I was confused that I couldn't find a purple set item among the legendary sets.
I think going by what the game actually displays should take priority over what the file name is.
![image](https://user-images.githubusercontent.com/10331302/82526252-d35dd200-9b33-11ea-9f9b-4ccb842ff37a.png)

**Comment by Malgardian** [comment]
Yeah, it's just that the purple colour is a bit randomly distributed among the items. The current sorting is what BeaverusIV originally chose and I continued to use.

**Comment by TheWagi** [comment]
Hey o/

The file name are indeed set to epic but the rarity tag is set to Legendary.

Wagi
