### ISSUE TITLE
Priest of Ba'al Hammon set

### ISSUE THREAD

**Issue by markotuna** [Malgardian/TQCollector#17]
![image](https://user-images.githubusercontent.com/82469901/114601899-4f09c580-9c96-11eb-9521-39b1f6334cf7.png)
Torso and helm also drop but arent listed in there. The ring is listed although unobtainable and completely screwed up.

**Comment by Malgardian** [comment]
Only the armband drops. All other parts don't as far as I can see. So I'm removing the ring as well.
