### ISSUE TITLE
Closing filter options window causes TQCollector to crash

### ISSUE THREAD

**Issue by weelillad** [Malgardian/TQCollector#2]
First off, thanks for updating this for Atlantis!

As described, opening the filter options window then closing it, either via the "Save" button or the window's close button, consistently causes the program to crash. This happens regardless of whether any filter options were changed. The good news is, any changes are reflected correctly when the program is re-opened. Therefore this is just a minor inconvenience.

Hope you can track the issue down and resolve it, let me know if I can provide any more information.

**Comment by Malgardian** [comment]
Huh, that's a weird one. Do you have Ragnarök and/or Atlantis installed?

**Comment by weelillad** [comment]
I only have Ragnarok, but not Atlantis.

**Comment by Malgardian** [comment]
Do you have the "R" button in the main window enabled?

**Comment by weelillad** [comment]
Yes, it is enabled.

**Comment by Malgardian** [comment]
Please try using the version 1.2.1 I just released.

**Comment by weelillad** [comment]
Issue seems to be fixed in v 1.2.1, thanks!
