### ISSUE TITLE
The Trackmaster - Wrong Category

### ISSUE THREAD

**Issue by TheWagi** [Malgardian/TQCollector#25]
Hey o/

"The Trackmaster" set from Ragnarok is an Epic set according to the rarity tag.
However, its under Legendary on TQCollector.

File | tagArmor | Item Name
- z_tracksuit.dbr | x2tagZArmor003 | Sweat Bands
- z_tracksuit.dbr | x2tagZArmor004 | Track Pants
- z_tracksuit.dbr | x2tagZArmor002 | Headband
- z_tracksuit.dbr | x2tagZArmor001 | Running Jacket

TQDB: https://www.tq-db.net/en/set/the-trackmaster

Wagi

**Comment by Malgardian** [comment]
I suppose this one can be moved as it drops in both Epic and Legendary.

**Comment by Malgardian** [comment]
Fixed in an upcoming release
