### ISSUE TITLE
Shadesong - Wrong Rarity

### ISSUE THREAD

**Issue by TheWagi** [Malgardian/TQCollector#26]
Hey o/

TQDB: https://www.tq-db.net/en/equipment/shadesong
is under Legendary Clubs but it should be under Epic Clubs

File | Tag | Item Name
us_e_umbralraiment.dbr | tagUWeapon193 | Shadesong

Wagi

**Comment by Malgardian** [comment]
Disagree, it's where it belongs. The filename is the indicator here.
