### ISSUE TITLE
Missing Doomfang diadem

### ISSUE THREAD

**Issue by tnm-l** [Malgardian/TQCollector#27]
Hi ,

The Doomfang diadem isn't taken into account by TQCollector (v 1.3.0.0). I recently found this object in the game (version 2.10.19714 - no mod installed) and it doesn't appear in the list of Monster Infrequent items. I witnessed this with the legendary version (Records\XPack3\Items\EquipmentArmor\Helm\MI_L_SerpentoidMage.dbr), but no other version of the object seems to be listed.

Thanks for maintaining this tool in any case.

**Comment by Malgardian** [comment]
Thanks for the report!

It seems like they did not drop at some point before the recent patch so I listed them intentionally commented out in the itemdb.xml file. If they are available in the game now, I should enable that entry.

I won't get around to that until at least the weekend, however, so if you're impatient you can just remove the comment in the itemdb.xml file yourself :)

**Comment by tnm-l** [comment]
No worries, I'll wait happily. And thanks for the workaround!

**Comment by Malgardian** [comment]
Fixed in the new release
