### ISSUE TITLE
tqvault files are not properly recognized/read

### ISSUE THREAD

**Issue by AmyntasSynth** [Malgardian/TQCollector#28]
Currently, the directory setup window will only allow me to click ok, if I rename the file extensions of the vault files from **.vault.json** to **.json**.
Although if I do so, I get an error message telling me "Error loading .vault files.

![1](https://user-images.githubusercontent.com/57623497/164969186-ea6945b4-46da-4cc9-b9b6-512e0e6e4e44.PNG)
![2](https://user-images.githubusercontent.com/57623497/164969188-1815225a-adfe-4dba-b6d5-a32b36ea8671.PNG)
"

**Comment by hguy** [comment]
Since TQVaultAE 4.0 the vault file format has changed from binary (.vault) to json (.vault.json).

**Comment by Malgardian** [comment]
What hguy said. Your only options at this point are either to downgrade TQVault to a previous version or to wait if/until I get around to determine what I'm going to do about that change on TQC's end.

**Comment by Malgardian** [comment]
Fixed with Release v1.4
