### ISSUE TITLE
Filter option "Use checkbox instead of bold" has no effect

### ISSUE THREAD

**Issue by weelillad** [Malgardian/TQCollector#3]
Happened across another minor bug, I think. As the title says, toggling the filter option does not seem to change anything. I'd expected it to indicate items that I possess with a checked checkbox beside the item name.

**Comment by Malgardian** [comment]
Another thing that's rarely used, I think. I'll have a look. Thanks for your bug hunting!

**Comment by Malgardian** [comment]
Seems to work for me?

**Comment by weelillad** [comment]
It only works in the "Sets" tab, but not in any of the other tabs. I'm using v1.2.1. `config.xml` correctly shows `<UseCheckBox>true</UseCheckBox>`.

**Comment by weelillad** [comment]
Also, when "Use checkbox" is enabled, the item mouseover tooltip does not appear. Should this be a new issue?

**Comment by Malgardian** [comment]
Works in the MI tab for me as well. But you're correct that it doesn't work in the others. Nah, here is fine.

**Comment by weelillad** [comment]
Oops, I'd filtered MI out, hence I didn't check whether things work there. :stuck_out_tongue:

**Comment by Malgardian** [comment]
Fixed in 1.2.2
The tooltip fix is a bit of a workaround, but a full fix would require moving the whole project to a newer version of .NET which is not something I want to do if I can avoid it. Let me know whether there's any further issues with my current solution.

**Comment by weelillad** [comment]
Everything looks good, thanks!
