### ISSUE TITLE
missing MI "Northerner's Axe" Eternal Ember 

### ISSUE THREAD

**Issue by gegeIII** [Malgardian/TQCollector#32]
Hello, 

►Firstly, thanks for this tool, as a compulsive collector ("Gotta catch 'em all" generation, or something like that ^^), i enjoy it a lot :D (71.95% right now... still have a lot of things to stash in my Vault^^)

►Secondly , as said in title, "Northerner's Axe" dropped by bandits is not in the checklist
![B](https://github.com/Malgardian/TQCollector/assets/104711400/867a3c15-99f0-419b-a955-48110e06e9c6)

►Thirdly, same kind of thing with a parchment, "The Pieces" is not in the list ... but maybe there is a mistake, since it's found at the same place than "Actor's note" and "Poet's jotting" it could be the "Behind the wall" of the checklist
![A](https://github.com/Malgardian/TQCollector/assets/104711400/04dfbe9e-141c-4451-9a44-c454606c8f3e)

►fourthly, just a little +1 to the other topic suggesting of adding the scrolls and others as optional to the check-list  \(^_^)/ 
(I collected them anyway, the 97 dyes, the potions, the quest items, ... "Compulsive Collector" should be my name :D)
![C](https://github.com/Malgardian/TQCollector/assets/104711400/9f3028c6-7fac-4e9d-b433-688cf6c6af84)  ![E](https://github.com/Malgardian/TQCollector/assets/104711400/01478da5-9e21-479e-b8a6-38ed589d4dd7) ![F](https://github.com/Malgardian/TQCollector/assets/104711400/272f3e09-6a12-4d4d-b15b-74b4c8ea62e7) ![D](https://github.com/Malgardian/TQCollector/assets/104711400/036db158-e5d4-484e-a145-72a47c1c5ffe)

Thanks again for your work, 
Have a nice day

**Comment by Malgardian** [comment]
Fixed in an upcoming release
