### ISSUE TITLE
Wrong item in Umbra Raiment set

### ISSUE THREAD

**Issue by graceoflives** [Malgardian/TQCollector#4]
The Umbra Raiment set has an item named Shadesong. The correct item should be Soul Quencher
Link in tq-db.net: https://www.tq-db.net/en/set/umbral-raiment

**Comment by Malgardian** [comment]
Shadesong's dbr file is literally called "us_e_umbralraiment.dbr", so I assume it was part of the set at some point, but got removed? I'll update it, thanks.

**Comment by Malgardian** [comment]
Fixed in 1.2.2
