### ISSUE TITLE
App cannot recognize sets from Atlantis DLC 

### ISSUE THREAD

**Issue by graceoflives** [Malgardian/TQCollector#5]
I have the sets (Turdulic Battle Casque, Reptilian Limbs, The Mollusc) in one of the vaults, along with some other normal sets. TQCollector recogize the others, but not those sets.
full set info:

- Turdulic Battle Casque: https://www.tq-db.net/en/set/turdulic-battle-gear
- Reptilian Limbs: https://www.tq-db.net/en/set/reptilian-limbs
- The Mollusc: https://www.tq-db.net/en/set/the-mollusc

**Comment by Malgardian** [comment]
Fixed in 1.2.2
