### ISSUE TITLE
[1.2.2] Shadesong not appear in Epic Clubs

### ISSUE THREAD

**Issue by graceoflives** [Malgardian/TQCollector#7]

**Comment by Malgardian** [comment]
It's in Legendary clubs as intended, isn't it?

**Comment by graceoflives** [comment]
it is an epic one: https://www.tq-db.net/en/equipment/shadesong
![image](https://user-images.githubusercontent.com/20889772/60059677-a6345400-9717-11e9-8771-20a6baac5509.png)

**Comment by Malgardian** [comment]
It might be blue, but it only drops in Epic and Legendary. That's why I put it in the Legendary category.
